markdown: kramdown
permalink: /:title.html
url: https://viper140.github.io/
baseurl: ""      # 这个我们不用填写
lsi: true
rouge: true
safe: true

# presonal config
title: Vicotr's Blog
SEOTitle: 你的博客 | You Blog    	 #显示在浏览器上搜索的时候显示的标题
# header-img: img/post-bg-rwd.jpg  	#显示在首页的背景图片
feed: /atom.xml
comments: disqus
email: You@gmail.com
description: Vicotr's Blog	 #网站介绍

author:
  name: Vicotr
  nickname: Vicotr
  # email: ixxoo.me@gmail.com
  # gmail: ixxoo.me@gmail.com
  # qqmail: http://mail.qq.com/cgi-bin/qm_share?t=qm_mailme&email=GnZzcX94f257WmtrNHl1dw
  # qqlist: http://list.qq.com/cgi-bin/qf_invite?id=eff06957927177ae5d491bb3c18e4a3c5fc328c95b6ae04f
  site: https://viper140.github.io/

seo:
  keyword:
  description:
